name: Build
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 17
          cache: gradle
      - name: Check locale strings
        run: python3 scripts/check_locale_strings.py
      - name: Unit tests and lint
        run: ./gradlew testDebugUnitTest lintDebug
      - name: Upload test and lint reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: test-and-lint-reports
          path: |
            app/build/reports/tests/
            app/build/reports/lint-results-debug.html
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 17
          cache: gradle
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 -d > "$RUNNER_TEMP/android_keystore.keystore"
      - name: Build the app
        run: ./gradlew assembleRelease -PshowUpdateButton=true -PuniversalApk -Pandroid.injected.signing.store.file=$RUNNER_TEMP/android_keystore.keystore -Pandroid.injected.signing.store.password=${{ secrets.PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.PASSWORD }}
      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v7
        with:
          name: app-arm64-v8a-release.apk
          path: app/build/outputs/apk/release/app-arm64-v8a-release.apk
      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v7
        with:
          name: app-x86_64-release.apk
          path: app/build/outputs/apk/release/app-x86_64-release.apk
      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v7
        with:
          name: app-armeabi-v7a-release.apk
          path: app/build/outputs/apk/release/app-armeabi-v7a-release.apk
      - name: Upload universal APK
        uses: actions/upload-artifact@v7
        with:
          name: app-universal-release.apk
          path: app/build/outputs/apk/release/app-universal-release.apk
      - name: Upload x86 APK
        uses: actions/upload-artifact@v7
        with:
          name: app-x86-release.apk
          path: app/build/outputs/apk/release/app-x86-release.apk